name = "cococasing-contact-worker"
main = "src/index.ts"
compatibility_date = "2023-10-25"
compatibility_flags = [ "nodejs_compat" ]

[vars]
# Set this to true for testing the Coco Casing app locally
CORS_ALLOW_LOCALHOST = false

USE_FAKE_EMAIL_SENDING = false
SHOULD_FAKE_EMAIL_SENDING_FAIL = false
RECIPIENT_EMAIL = "ditrichb@gmail.com"
RECIPIENT_NAME = "Bence Ditrich"

USE_FAKE_SITEVERIFY = false
SHOULD_FAKE_SITEVERIFY_FAIL = false
